version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_north_ink
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pasroot
      MYSQL_DATABASE: north-ink
      MYSQL_PASSWORD: pasroot
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
