version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_north_ink
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pasroot
      MYSQL_DATABASE: north-ink
      MYSQL_PASSWORD: pasroot
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

azure:
  storage:
    account-name: <storagenorthink>
    account-key: <amaBLvDVPkaVUeYMblFl5aggc5+6YtiD0FmfEgTy0UOZ8GIj/9cBH5PRWwLv/haKeU/2dMVQudR/+AStbBX59g==>
    endpoint: <https://storagenorthink.blob.core.windows.net/imagens>
